# Generated by Django 4.2.16 on 2025-02-10 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_authorization', models.BooleanField(verbose_name="I have read and understood the <a href='https://www.nau.edu.pt/legal/politica-de-privacidade/'rel='noopener' target='_blank'>Privacy Policy</a>")),
                ('favorite_movie', models.CharField(max_length=100, verbose_name='Fav Flick')),
                ('employment_situation', models.TextField(choices=[('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Public service contract', 'Public service contract'), ('Private institution contract', 'Private institution contract'), ('Self employed entrepreneur', 'Self employed entrepreneur'), ('Other', 'Other')], verbose_name='Employment situation')),
                ('allow_newsletter', models.BooleanField(verbose_name="I have read and agree to give my <a target='_blank' href='https://www.nau.edu.pt/legal/consentimento-para-o-envio-de-newsletters/'>consent to the sending of newsletters</a>")),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
