# Generated by Django 4.2.20 on 2025-04-11 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrainfo',
            options={'verbose_name': 'Extra Info', 'verbose_name_plural': 'Extra Info entries'},
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='allow_newsletter',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='employment_situation',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='favorite_movie',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us a bit about yourself.', verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='favorite_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('go', 'Go')], max_length=50, verbose_name='Favorite programming language'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='password_hint',
            field=models.CharField(blank=True, help_text='Optional hint to remember your password.', max_length=255, verbose_name='Password hint'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='registration_token',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Registration token (internal)'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='I accept the Terms and Conditions.'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='wants_newsletter',
            field=models.BooleanField(default=False, verbose_name='Subscribe to newsletter'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='data_authorization',
            field=models.BooleanField(verbose_name="I have read and understood the <a href='https://www.nau.edu.pt/legal/politica-de-privacidade/' rel='noopener' target='_blank'>Privacy Policy</a>"),
        ),
    ]
